#!/usr/bin/env sh


# colored man
man() {
    env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}

cat() {
    local out colored
    out=$(/bin/cat $@)
    colored=$(echo $out | pygmentize -f console -g 2>/dev/null)
    [[ -n $colored ]] && echo "$colored" || echo "$out"
}

mcd() {
    mkdir -p $@
    cd $@
}

## git
gitclone() {
  # from https://gist.github.com/nicferrier/2277987
  REPOSRC=$1
  LOCALREPO=$2
  
  # We do it this way so that we can abstract if from just git later on
  LOCALREPO_VC_DIR=$LOCALREPO/.git
  
  if [ ! -d $LOCALREPO_VC_DIR ]
  then
      git clone $REPOSRC $LOCALREPO
  else
      cd $LOCALREPO
      git pull $REPOSRC
  fi
}

## cleanup
arch_clean() {
  yaourt -Rns $(pacman -Qtdq)
}

## update
arch_update() {
  yaourt -Syu
}
