#!/usr/bin/env sh

export PATH=${HOME}/.config/setup/bin:$PATH
export LOCAL_ROOT=${HOME}/.local

if [ -n "${CONDA_ROOT+1}" ]; then
  export PATH=${CONDA_ROOT}/bin:$PATH
fi

if [ -n "${CUDA_ROOT+1}" ]; then
  export PATH=${CUDA_ROOT}/bin:$PATH
  export LD_LIBRARY_PATH=${CUDA_ROOT}/lib64:$LD_LIBRARY_PATH
fi

if [ -n "${TORCH_ROOT+1}" ]; then
    source ${TORCH_ROOT}/install/bin/torch-activate
fi

if [ -n "${BREW_ROOT+1}" ]; then
  export PATH=${BREW_ROOT}/bin:${BREW_ROOT}/sbin:$PATH
  export MANPATH=${BREW_ROOT}/share/man:$MANPATH
  export INFOPATH=${BREW_ROOT}/share/info:$INFOPATH
fi

if [ -n "${LOCAL_ROOT+1}" ]; then
  mkdir -p ${LOCAL_ROOT}/bin
  mkdir -p ${LOCAL_ROOT}/lib
  export PATH=${LOCAL_ROOT}/bin:$PATH
  export LD_LIBRARY_PATH=${LOCAL_ROOT}/lib:$LD_LIBRARY_PATH
fi

if [ -n "${VMAP_ROOT+1}" ]; then
  mkdir -p ${VMAP_ROOT}
  source ~/.config/setup/env/vmap
fi

export EDITOR=vim
