#!/usr/bin/env sh

if [ -n "${CONDA_ROOT+1}" ]; then
    export PATH=${CONDA_ROOT}/bin:$PATH
fi

if [ -n "${CUDA_ROOT+1}" ]; then
    export PATH=${CUDA_ROOT}/bin:$PATH
    export LD_LIBRARY_PATH=${CUDA_ROOT}/lib64:$LD_LIBRARY_PATH
fi

if [ -n "${TORCH_ROOT+1}" ]; then
    source ${TORCH_ROOT}/install/bin/torch-activate
fi

if [ -n "${BREW_ROOT+1}" ]; then
  export PATH=${BREW_ROOT}/bin:${BREW_ROOT}/sbin:$PATH
  export MANPATH=${BREW_ROOT}/share/man:$MANPATH
  export INFOPATH=${BREW_ROOT}/share/info:$INFOPATH
fi

if [ -n "${LOCAL_ROOT+1}" ]; then
    export PATH=${LOCAL}/bin:$PATH
    export LD_LIBRARY_PATH=${LOCAL}/lib:$LD_LIBRARY_PATH
fi

export EDITOR=vim
