#!/bin/sh

gitclone() {
  # from https://gist.github.com/nicferrier/2277987
  REPOSRC=$1
  LOCALREPO=$2
  
  # We do it this way so that we can abstract if from just git later on
  LOCALREPO_VC_DIR=$LOCALREPO/.git
  
  if [ ! -d $LOCALREPO_VC_DIR ]
  then
      git clone $REPOSRC $LOCALREPO
  else
      cd $LOCALREPO
      git pull $REPOSRC
  fi
}


gitclone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/vundle
gitclone https://github.com/tarjoilija/zgen.git ~/.config/zgen
gitclone https://github.com/syl20bnr/spacemacs ~/.emacs.d
