#!/usr/bin/env sh

set -x
set -e

sudo systemctl enable tlp.service
sudo systemctl start tlp.service
sudo systemctl enable tlp-sleep.service
sudo systemctl start tlp-sleep.service
sudo systemctl enable systemd-rfkill.service
sudo systemctl start systemd-rfkill.service
