#!/usr/bin/env sh
WALLPAPER="${HOME}/.config/wallpaper"

if [ ! -d $WALLPAPER ];
then
  echo "Downloading wallpaper... Warning: this is a very large download!"
  wget -O wallpaper.zip http://imgur.com/a/SPmIR/zip
  aunpack wallpaper.zip -X ${WALLPAPER}
fi
