---
- name: Machine Learning
  hosts: all
  tasks:
    - import_tasks: tasks/os.yml
    - name: install jupyter
      shell: "{{ conda_bin }}/conda install -y -c conda-forge jupyterlab"
    - name: install pytorch
      shell: "{{ conda_bin }}/conda install pytorch torchvision -c pytorch -c nvidia -c conda-forge"
